// friendly-labels.ts — single source of truth for explaining Dear User's
// recommendations in plain Danish that the Lovable audience can understand.
//
// Every consumer (dashboard cards, chat action menu, analyze report tool
// section) should go through friendlyLabel() so the wording stays consistent.
// Previously each surface reinvented its own copy and tool-recs (Firecrawl,
// Vercel MCP, …) slipped through with just the raw technical name.
//
// Structure per label:
//   title    — short Danish headline (falls back to original if unknown)
//   summary  — "Hvad er det?" in one plain sentence
//   benefit  — "Hvad bliver bedre?" — what the user actually gains
//
// Any of the three can be undefined for unknown titles; callers should
// show whatever exists and omit missing lines.

export interface FriendlyLabel {
  title: string;
  summary?: string;
  benefit?: string;
}

interface LabelRule {
  match: RegExp;
  label: FriendlyLabel;
}

// ===========================================================================
// Narrative recommendations (generated by Dear User's own analyze + audit)
// ===========================================================================

const NARRATIVE_RULES: LabelRule[] = [
  {
    match: /enable agent memory/i,
    label: {
      title: 'Lad din assistent huske dine rettelser',
      summary: 'Når du retter din assistent, kan rettelsen gemmes så den ikke gentages.',
      benefit: 'Du skal ikke forklare det samme igen og igen, hver gang I starter forfra.',
    },
  },
  {
    match: /add quality hooks/i,
    label: {
      title: 'Fang fejl automatisk mens du arbejder',
      summary: 'Dit system kan køre en hurtig kontrol hver gang en fil ændres.',
      benefit: 'Du opdager problemer med det samme — ikke først når noget går galt senere.',
    },
  },
  {
    match: /wrap .+ in an mcp server/i,
    label: {
      title: 'Gør dit script til et værktøj din assistent kan bruge',
      summary: 'Scripts du kører manuelt kan pakkes ind så assistenten kalder dem selv.',
      benefit: 'Du slipper for at kopiere kommandoer frem og tilbage — assistenten gør det direkte.',
    },
  },
  {
    match: /catch scope creep/i,
    label: {
      title: 'Stop med at lave mere end aftalt',
      summary: 'Nævn det når assistenten begynder at lave ekstra ting udover det du bad om.',
      benefit: 'Du bruger mindre tid på at rydde op i uventede ændringer og får hurtigere det du faktisk ville have.',
    },
  },
  {
    match: /don.?t accept .it should work|demand verification/i,
    label: {
      title: 'Bed altid om bevis for at det virker',
      summary: 'I stedet for at stole på "det burde virke": bed om et konkret tjek eller test.',
      benefit: 'Færre tilbageslag fordi problemer fanges mens de er små — ikke efter deploy.',
    },
  },
  {
    match: /calibrate the ask\/do line/i,
    label: {
      title: 'Aftal hvornår assistenten må handle selv',
      summary: 'Skriv ned hvad assistenten må gøre uden at spørge, og hvad den skal spørge om først.',
      benefit: 'Du behøver ikke forklare det forfra hver gang — og du undgår overraskelser.',
    },
  },
  {
    match: /name the tone mismatch/i,
    label: {
      title: 'Sig til når tonen ikke passer',
      summary: 'Hvis svaret føles for teknisk eller for fladt, sig det.',
      benefit: 'Assistenten tilpasser sig, så du får svar på dit niveau fremover.',
    },
  },
  {
    match: /upgrade repeating manual tasks/i,
    label: {
      title: 'Automatiser de ting du laver igen og igen',
      summary: 'Opgaver du gentager manuelt hver uge kan som regel køre af sig selv.',
      benefit: 'Du vinder tid og laver færre fejl — computeren glemmer ikke et step.',
    },
  },
  {
    match: /^\d+ project.*uncommitted/i,
    label: {
      title: 'Du har ting der ikke er gemt i Git',
      summary: 'Nogle af dine filer er ændret men ikke gemt i din version-historik.',
      benefit: 'Hvis din computer crasher nu, mister du arbejdet. Gem det så du har en kopi.',
    },
  },
  {
    match: /stale project.*haven.?t been touched/i,
    label: {
      title: 'Et projekt ligger og samler støv',
      summary: 'Et af dine projekter er ikke blevet rørt i over 60 dage.',
      benefit: 'Overvej om det skal genoptages eller arkiveres — du får mere fokus på det du faktisk arbejder med.',
    },
  },
  {
    match: /show repeated .fix again. commits/i,
    label: {
      title: 'Du fixer det samme flere gange',
      summary: 'Der er tegn på at samme problem fixes igen og igen.',
      benefit: 'Typisk betyder det at noget er uklart — enten koden eller instruktionen til assistenten. Løs det én gang og spar mange gentagelser.',
    },
  },
];

// ===========================================================================
// Tool-catalog recommendations — MCP servers, hooks, skills, GitHub repos
// ===========================================================================

const TOOL_RULES: LabelRule[] = [
  {
    match: /^firecrawl$/i,
    label: {
      title: 'Firecrawl — din assistent kan læse hjemmesider',
      summary: 'En web-skraber der lader din assistent læse indholdet af en hjemmeside pænt formateret.',
      benefit: 'Du slipper for at kopiere og indsætte fra artikler, dokumentation eller produktsider — din assistent kan læse dem selv.',
    },
  },
  {
    match: /^exa search$/i,
    label: {
      title: 'Exa Search — bedre søgeresultater til din assistent',
      summary: 'Et søgesystem lavet specifikt til AI-assistenter, hurtigere og mere præcist end almindelig web-søgning.',
      benefit: 'Din assistent finder præcise svar på faglige spørgsmål og relevante referencer hurtigere.',
    },
  },
  {
    match: /^vercel mcp$/i,
    label: {
      title: 'Vercel MCP — styr din Vercel-konto fra assistenten',
      summary: 'Forbinder din assistent med din Vercel-konto, hvor dine hjemmesider og apps bor.',
      benefit: 'Du kan deploye, tjekke status eller finde fejl uden at åbne Vercel-dashboardet selv.',
    },
  },
  {
    match: /^context7$/i,
    label: {
      title: 'Context7 — opdateret dokumentation til din assistent',
      summary: 'Giver din assistent adgang til den nyeste dokumentation for kode-biblioteker.',
      benefit: 'Stopper med at gætte på kommandoer og bruger den rigtige syntaks fra første forsøg.',
    },
  },
  {
    match: /^auto-build after edit$/i,
    label: {
      title: 'Automatisk tjek efter redigering',
      summary: 'Kører en hurtig kontrol hver gang din assistent ændrer en fil.',
      benefit: 'Du opdager fejl med det samme i stedet for først når du skal bruge resultatet.',
    },
  },
  {
    match: /^claude-code-prompt-improver$/i,
    label: {
      title: 'Prompt-hjælper',
      summary: 'Fanger uklare instruktioner før din assistent går i gang med arbejdet.',
      benefit: 'Du får bedre svar fordi assistenten beder dig præcisere, hvis noget er tvetydigt.',
    },
  },
  {
    match: /^playwright$/i,
    label: {
      title: 'Playwright — lad din assistent teste hjemmesider',
      summary: 'Din assistent kan åbne en browser, klikke rundt og tjekke om din hjemmeside virker.',
      benefit: 'Du slipper for at teste manuelt efter hver ændring.',
    },
  },
  {
    match: /^github( mcp)?$/i,
    label: {
      title: 'GitHub — din assistent kan arbejde direkte i dine projekter',
      summary: 'Forbinder din assistent med GitHub, hvor koden ligger.',
      benefit: 'Din assistent kan læse issues, lave pull requests og gennemse ændringer uden at du skifter værktøj.',
    },
  },
  {
    match: /^supabase( mcp)?$/i,
    label: {
      title: 'Supabase — assistenten kan arbejde med din database',
      summary: 'Forbinder din assistent med din Supabase-database.',
      benefit: 'Spørgsmål om data kan besvares direkte — assistenten slår op i stedet for at gætte.',
    },
  },
  {
    match: /^notion( mcp)?$/i,
    label: {
      title: 'Notion — din assistent kan læse og skrive i dine sider',
      summary: 'Forbinder din assistent med dine Notion-sider og databaser.',
      benefit: 'Dine noter, dokumenter og tracker-sider er tilgængelige for assistenten uden copy-paste.',
    },
  },
];

// ===========================================================================
// Lookup
// ===========================================================================

/**
 * Resolve a raw recommendation title into a Lovable-friendly label.
 * Callers should prefer the returned fields; for unknown titles we pass
 * the original title through and leave summary/benefit undefined so the
 * UI can decide how to handle the fallback (e.g. show the DB text_snippet).
 */
export function friendlyLabel(title: string): FriendlyLabel {
  for (const rule of [...NARRATIVE_RULES, ...TOOL_RULES]) {
    if (rule.match.test(title)) return rule.label;
  }
  // Fallback: just the original title, stripped of backticks that confuse
  // users reading the dashboard.
  return { title: title.replace(/`/g, '') };
}
